[package]
name = "agave-shred-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
solana-pubkey = { version = "4.3.0", default-features = false }

[dependencies.solana-ledger]
path = "../ledger"
features = ["agave-unstable-api"]

[[bin]]
name = "fuzz_shred_deserialize"
path = "fuzz_targets/fuzz_shred_deserialize.rs"
test = false
doc = false
bench = false

[workspace]

[patch.crates-io]
librocksdb-sys = { git = "https://github.com/anza-xyz/rust-rocksdb", rev = "4dba80dfe9434e595a971f5b2985ff9ba4fb31e7" }
rocksdb = { git = "https://github.com/anza-xyz/rust-rocksdb", rev = "4dba80dfe9434e595a971f5b2985ff9ba4fb31e7" }
